package gui;



import algorithm.AntsAlgorithm;
import algorithm.Params;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karol
 */
/*
Klasa GUI dziedziczy po JFrame
*/
public class GUI extends javax.swing.JFrame {

    /*
    Parametry, które wczytuje przy pomocy GUI. oraz ich metody dostępowe
    */
    private int numberAnts;
    private int time;
    private double alpha;
    private double beta;
    private double rho;
    private double q;
    private  String filename;
    private boolean read = true;
    
    
    public GUI() {
        initComponents();
        
    }
    
  
    
    
    public int getNumberAnts()
    {
        return numberAnts;
    }
    
    public int getTime()
    {
        return time;
    }
    
    public double getAlpha()
    {
        return alpha;
        
    }
    
    public double getBeta()
    {
        return beta;
    }
    
    public double getRho()
    {
        return rho;
    }
    
    public double getQ()
    {
        return q;
    }
    
    public String getFileName()
    {
        return filename;
    }
 /*
    metoda ktora sprawdza poprawność pobranych danych. Jeśli dane poprawne to przesyła do Klasy Params.
    W przeciwnym wypadku drukuje odpowiedni napis do textArea.
    */
    private void dataValidation(Params param)
	{
		jTextArea1.setText(null);
		try{
			numberAnts = Integer.parseInt(textNumberAnts.getText());
			if(numberAnts < 0){
				jTextArea1.setText("Liczba mrówek nie może być ujemna");
                                read = false;
                        }
			else
				param.setNumberAnts(numberAnts);

                        time = Integer.parseInt(textTime.getText());
                        if(time < 0){
				jTextArea1.setText("Ilość iteracji nie może być ujemna");
                                         read = false;
                        }
			else
				param.setTime(time); 
                        alpha = Double.parseDouble(textAlpha.getText());
                        if(alpha < 0){
				jTextArea1.setText("Parametr alfa nie może być ujemny");
                                         read = false;
                        }
			else
				param.setAlpha(alpha); 
                        beta = Double.parseDouble(textBeta.getText());
                        if(beta < 0){
				jTextArea1.setText("Parametr beta nie może być ujemny");
                                         read = false;
                        }
			else
				param.setBeta(beta); 
                        rho = Double.parseDouble(textRho.getText());
                        if(rho < 0){
				jTextArea1.setText("Współczynnik parowania feromonu nie może być ujemny");
                                         read = false;
                        }
			else
			{
				if(rho > 0 && rho <1)
					param.setRho(rho);
                                else{
					jTextArea1.setText("Współczynnik parowania feromonu musi być z przedziału (0;1)");
                                                 read = false;
                                    }
			}
                        q = Double.parseDouble(textQ.getText());
                        if(q < 0){
				jTextArea1.setText("Ilość pozostawionego feromonu nie może być ujemna");
                                         read = false;
                        }
			else
			{
				
				param.setQ(q);
                                
			}
                        try{
                            if(filename.endsWith(".txt"))
                                param.setFileName(filename);
                            else {
                                jTextArea1.setText("Zły format pliku. Podaj z końcówką .txt");
                                     read = false;
                        }
                        } catch(NullPointerException e)
                        {
                          jTextArea1.setText("Nie podano pliku");
                          read = false;
                        }
                        
        }    
		catch (NumberFormatException e) { 
		read = false; 
		jTextArea1.setText("Niepoprawny format danych"); 
	}
	}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textNumberAnts = new javax.swing.JTextField();
        textTime = new javax.swing.JTextField();
        textAlpha = new javax.swing.JTextField();
        textBeta = new javax.swing.JTextField();
        textRho = new javax.swing.JTextField();
        textQ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonStart = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        buttonFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("liczba mrówek");

        textNumberAnts.setText("10");
        textNumberAnts.setToolTipText("Całkowite większe od 0");
        textNumberAnts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumberAntsActionPerformed(evt);
            }
        });

        textTime.setText("100");
        textTime.setToolTipText("Całkowite większe od 0");
        textTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTimeActionPerformed(evt);
            }
        });

        textAlpha.setText("2.3");
        textAlpha.setToolTipText("Zmiennoprzecinkowe większe od 0.");
        textAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlphaActionPerformed(evt);
            }
        });

        textBeta.setText("3.2");
        textBeta.setToolTipText("Zmiennoprzecinkowe większe od 0.");
        textBeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBetaActionPerformed(evt);
            }
        });

        textRho.setText("0.3");
        textRho.setToolTipText("Z przedziału (0;1)");
        textRho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRhoActionPerformed(evt);
            }
        });

        textQ.setText("3.0");
        textQ.setToolTipText("Zmiennoprzecinkowa większa od 0.");
        textQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQActionPerformed(evt);
            }
        });

        jLabel2.setText("ilość iteracji");

        jLabel3.setText("parametr alpha");

        jLabel4.setText("parametr beta");

        jLabel5.setText("wsp. parowania ferom.");

        jLabel6.setText("ilość pozostaw. ferom.");

        jLabel7.setText("ścieżka");

        buttonStart.setBackground(new java.awt.Color(52, 207, 39));
        buttonStart.setForeground(new java.awt.Color(16, 25, 15));
        buttonStart.setText("Start");
        buttonStart.setToolTipText("Start programu");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        buttonExit.setBackground(new java.awt.Color(210, 43, 45));
        buttonExit.setForeground(new java.awt.Color(23, 16, 16));
        buttonExit.setToolTipText("Wyjście z programu");
        buttonExit.setLabel("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonFile.setToolTipText("Podaj pliki .txt");
        buttonFile.setLabel("Przeglądaj");
        buttonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textQ, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textRho, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textNumberAnts, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 192, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonFile)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textNumberAnts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textRho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(buttonFile)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    przycisk Start -> W tej metodzie waliduje dane. Jeśli są poprawne ( parametr read = true) wtedy przysyłam je 
    do klasy AntsAlgorithm wywołując jej konstruktor z odpowiednimi parametrami. 
    Następnie startuje wątek oraz drukuje wyniki do textArea.
    */
    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(null);
        Params param = new Params(); 
        dataValidation(param);
        if(read == true){
            try {
        AntsAlgorithm algorithm = new AntsAlgorithm(param); 
        algorithm.start(); 
        while(algorithm.isAlive()){
            
            jTextArea1.setText(AntsAlgorithm.getResult());
        }
        }
            catch(IOException | CloneNotSupportedException | NumberFormatException e)
                {
                   jTextArea1.setText("IOException lub CloneNotSupportedException lub NumberFormatException");
                }
        }
        
        
        
        
        
    }//GEN-LAST:event_buttonStartActionPerformed

    private void textNumberAntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumberAntsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumberAntsActionPerformed

    private void textTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTimeActionPerformed

    private void textAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlphaActionPerformed

    private void textBetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBetaActionPerformed

    private void textRhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRhoActionPerformed

    private void textQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed
/*
    Przycisk przeglądaj w GUI. Pobieram ścieżkę do pliku i zapisuje do filename. Dodatkowo wyświetlam w GUI przy użyciu
    Label domyślnie ustawionego na ścieżka.
    */
    private void buttonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        
        File f = chooser.getSelectedFile();        
        filename = f.getAbsolutePath();
        jLabel7.setText(filename);
        
    }//GEN-LAST:event_buttonFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonFile;
    private javax.swing.JButton buttonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textAlpha;
    private javax.swing.JTextField textBeta;
    private javax.swing.JTextField textNumberAnts;
    private javax.swing.JTextField textQ;
    private javax.swing.JTextField textRho;
    private javax.swing.JTextField textTime;
    // End of variables declaration//GEN-END:variables
}
